# Generated by Django 5.0.6 on 2024-05-23 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tune',
            name='attempt_download_on_create',
            field=models.BooleanField(default=False),
        ),
    ]
