# Generated by Django 5.0.6 on 2024-05-17 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_tag_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tune',
            name='file_name',
            field=models.CharField(blank=True, editable=False, max_length=200, unique=True),
        ),
    ]
