# Generated by Django 5.0.6 on 2024-05-20 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_tune_file_exists'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tune',
            name='file_exists',
        ),
    ]
