# Generated by Django 5.0.6 on 2024-05-21 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_remove_tune_file_exists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tune',
            name='youtube_id',
            field=models.CharField(max_length=75, unique=True),
        ),
    ]
