# Generated by Django 5.0.6 on 2024-05-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_alter_tune_youtube_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tune',
            name='file_name',
            field=models.CharField(blank=True, editable=False, max_length=200),
        ),
    ]
