# Generated by Django 5.0.6 on 2024-05-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_alter_tune_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tune',
            name='file_name',
            field=models.CharField(editable=False, max_length=200, unique=True),
        ),
    ]
