# Generated by Django 5.0.6 on 2024-05-27 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_alter_tune_album_alter_tune_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tune',
            name='album',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='music.album'),
        ),
        migrations.AlterField(
            model_name='tune',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='music.genre'),
        ),
    ]
