# Generated by Django 5.0.6 on 2024-06-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_album_track_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='track_count',
            field=models.SmallIntegerField(default=1),
        ),
    ]
