# Generated by Django 5.0.6 on 2024-06-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_rawtunestring_id_1_rawtunestring_id_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawtunestring',
            name='possible_duplicate',
            field=models.BooleanField(default=False),
        ),
    ]
