# Generated by Django 5.0.6 on 2024-06-14 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0014_rawtunestring_possible_duplicate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawtunestring',
            name='id_1',
        ),
        migrations.RemoveField(
            model_name='rawtunestring',
            name='id_2',
        ),
        migrations.RemoveField(
            model_name='rawtunestring',
            name='id_3',
        ),
        migrations.RemoveField(
            model_name='rawtunestring',
            name='id_4',
        ),
        migrations.RemoveField(
            model_name='rawtunestring',
            name='id_5',
        ),
    ]
