# Generated by Django 5.0.6 on 2024-06-14 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0015_remove_rawtunestring_id_1_remove_rawtunestring_id_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawtunestring',
            name='possible_duplicate',
        ),
    ]
