# Generated by Django 5.0.6 on 2024-06-14 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0018_alter_album_options_album_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='reference',
        ),
    ]
